# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"
  environment = { NODE_VERSION = "18.13.0" }


[context.production]
  publish = "output/"
  command = "make publish"
  environment = { NODE_VERSION = "18.13.0" }

[functions]
  node_bundler = "esbuild"

[[plugins]] 
  package = "netlify-plugin-cypress@10.0.3"

  [plugins.inputs.postBuild]
    enable = true
  
  [plugin.inputs]
    enable = false
    
[[redirects]]
  from = "/api/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok code
  force = true # ensure to always redirect